on:
  workflow_call:
    inputs:
      ssh_host:
        required: true
        type: string
      ssh_username:
        required: true
        type: string
      ssh_port:
        required: false
        type: number
        default: 9000
      dev_site_base_url:
        required: true
        type: string
        description: Base URL of the production site
      tested_paths:
        required: true
        type: string
        description: |
          JSON list of paths from the site of this project to run the checks against, without base URL
          For example,
          '["/contacts", "/login", "/products/123-mega-pack.html"]'
    secrets:
      PAGE_SPEED_INSIGHTS_KEY:
        required: true
      SSBRANCH_PSI_SSH_KEY:
        required: true
jobs:
  run_psi:
    runs-on: ubuntu-latest
    name: Running Page Speed Insights on a testing version of the site
    steps:
      - name: Deploy a branch
        uses: fifsky/ssh-action@master
        id: ssbranch-ssh-deploy
        with:
          host: ${{ inputs.ssh_host }}
          user: ${{ inputs.ssh_username }}
          key: ${{ secrets.SSBRANCH_PSI_SSH_KEY }}
          port: ${{ inputs.ssh_port }}
          args: -vvv
          command: |
            set -x
            [ -d ~/branches/${{ github.head_ref }}/repo ] && cd ~/branches/${{ github.head_ref }}/repo && git pull origin ${{ github.head_ref }} || rm -rf ~/branches/${{ github.head_ref }}/ && ssbranch create ${{ github.head_ref }} ${{ github.head_ref }} --no-interaction
      - name: Run Page Speed Insights
        uses: ./ssbranch-psi-action
        id: psi
        with:
          dev_site_base_url: ${{ inputs.dev_site_base_url }}
          ssbranch_subdomain_short: ${{ github.head_ref }}
          tested_paths: ${{ inputs.tested_paths }}
          threshold: 85
          psi_key: ${{ secrets.PAGE_SPEED_INSIGHTS_KEY }}
      - name: Leave comment with report results on PR
        id: comment_to_pr
        uses: marocchino/sticky-pull-request-comment@v2.2.0
        with:
          header: Page Speed Insights report for PR \#${{ github.event.pull_request.number }}
          hide_and_recreate: true
          message: ${{ steps.psi.outputs.report }}
      - name: Undeploy a branch
        uses: fifsky/ssh-action@master
        id: ssbranch-ssh-undeploy
        with:
          host: ${{ inputs.ssh_host }}
          username: ${{ inputs.ssh_username }}
          key: ${{ secrets.SSBRANCH_PSI_SSH_KEY }}
          port: ${{ inputs.ssh_port }}
          script: |
            set -x
            ssbranch remove ${{ github.head_ref }} --no-interaction
            rm -rf ~/branches/${{ github.head_ref }}
