on:
  workflow_call:
    inputs:
      ssh_host:
        required: true
        type: string
      ssh_username:
        required: true
        type: string
      ssh_port:
        required: false
        type: number
        default: 9000
      dev_site_base_url:
        required: true
        type: string
        description: Base URL of the production site
      tested_paths:
        required: true
        type: string
        description: |
          JSON list of paths from the site of this project to run the checks against, without base URL
          For example,
          '["/contacts", "/login", "/products/123-mega-pack"]'
      current_branch:
        required: true
        type: string
        description: "Just put ${{ \'${{ github.head_ref }}\' }} here when calling this workflow"
    secrets:
      PAGE_SPEED_INSIGHTS_KEY:
        required: true
      SSBRANCH_PSI_SSH_KEY:
        required: true
jobs:
  run_psi:
    runs-on: ubuntu-latest
    name: Running Page Speed Insights on a testing version of the site
    steps:
      - name: Deploy a branch
        uses: appleboy/ssh-action@v0.1.0
        id: ssbranch-ssh-deploy
        env:
          SSBRANCH_CREATE_NAME: ${{ secrets.current_branch }}
          SSBRANCH_CREATE_SUBDOMAIN: ${{ secrets.current_branch }}
        with:
          host: ${{ inputs.ssh_host }}
          username: ${{ inputs.ssh_username }}
          key: ${{ secrets.SSBRANCH_PSI_SSH_KEY }}
          passphrase: ''
          port: ${{ inputs.ssh_port }}
          envs: SSBRANCH_CREATE_NAME,SSBRANCH_CREATE_SUBDOMAIN
          script: "ssbranch create $SSBRANCH_CREATE_NAME $SSBRANCH_CREATE_SUBDOMAIN --no-interaction;"
          debug: true
      - name: Undeploy a branch
        uses: appleboy/ssh-action@master
        id: ssbranch-ssh-undeploy
        env:
          SSBRANCH_REMOVE_NAME: ${{ secrets.current_branch }}
        with:
          host: ${{ inputs.ssh_host }}
          username: ${{ inputs.ssh_username }}
          key: ${{ secrets.SSBRANCH_PSI_SSH_KEY }}
          port: ${{ inputs.ssh_port }}
          envs: SSBRANCH_REMOVE_NAME
          script: "bash -c \"ssbranch remove $SSBRANCH_REMOVE_NAME --no-interaction;\""
#      - name: Checkout repository
#        uses: actions/checkout@v1
#      - name: Run Page Speed Insights
#        uses: ./
#        id: psi
#        with:
#          dev_site_base_url: ${{ inputs.dev_site_base_url }}
#          ssbranch_subdomain_short: ${{ secrets.current_branch }}
#          tested_paths: ${{ inputs.tested_paths }}
#          threshold: 85
#          psi_key: ${{ secrets.page_speed_insights_key }}
#      - name: Format report results
#        id: format
#        uses: actions/github-script@v3
#        with:
#          script: |
#      - name: Leave comment with report results on PR
#        id: comment_to_pr
#        uses: marocchino/sticky-pull-request-comment@v2.2.0
#        with:
#          header: Page Speed Insights report for PR \#${{ github.event.pull_request.number }}
#          hide_and_recreate: true
#          message: ${{steps.psi.outputs.report}}
